# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: gitlab.pnnl.gov:4567/mass-spectrometry/corems:corems-base
#gitlab.pnnl.gov:4567/mass-spectrometry/corems:latest 
#python:3.7.5

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  
  paths:
    - .cache/pip
  

stages:
  - test
  - run
  - build
  
test-source:
  
  stage: test
  tags:
    - massspec
    - k8s 
    - rcint
    
  script:
    
    - python3.7 -V  # Print out python version for debugging
    - pip install -r requirements.txt
    - pip install pytest
    - pip install pytest-cov
    - ls .
    - python3.7 -c "import pathlib; [p.unlink() for p in pathlib.Path('.').rglob('tests/win_only/__init__.py')]"
    - pytest
  
  artifacts:
    paths:
      - doc/coverage_html_report  
   

run-job:
  
  stage: run
  tags:
    - massspec
    - k8s 
    - rcint
    
  script:
    
    - python3.7 -V  # Print out python version for debugging
    - pip install -r requirements.txt
    - pip install wheel
    - python3.7 setup.py sdist bdist_wheel
    - python3.7 setup.py bdist_wheel
    # an alternative approach is to install and run:
    #- pip install dist/*
    # run the command here

  artifacts:
    paths:
      - dist/*

docker-image:
  stage: build
  
  tags:
    - massspec
    - k8s 
    - rcint
    
    
  image:
    
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  
  script:
    
    - export DOCKER_CONFIG=/kaniko/.docker/
    - export GOOGLE_APPLICATION_CREDENTIALS=/kaniko/.docker/config.json  
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    


#pages:
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd doc ; make html
#    - mv build/html/ ../public/
#  artifacts:
#    paths:
#      - public
#  only:
#    - master
