version: '3.1'

services:
  molformdb:
    image: postgres
    restart: always
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env

volumes:
  db-volume:
