version: '3.1'

services:
  molformdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: molformula
      POSTGRES_USER: coremsdb
      POSTGRES_PASSWORD: coremsmolform
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  corems_notebook:
    image: corilo/corems:latest
    volumes:
      - ./data:/home/CoreMS/data
    ports:
      - 8888:8888
    container_name: corems 

volumes:
  db-volume:
