[MolecularFormulaSearch]
use_isotopologue_filter = false
isotopologue_filter_threshold = 33.0
isotopologue_filter_atoms = [ "Cl", "Br",]
use_runtime_kendrick_filter = false
use_min_peaks_filter = true
min_peaks_per_class = 15
url_database = "sqlite:///db/molformula.db"
db_jobs = 3
ion_charge = -1
min_hc_filter = 0.3
max_hc_filter = 3.0
min_oc_filter = 0.0
max_oc_filter = 1.2
min_op_filter = 2.0
use_pah_line_rule = false
min_dbe = 0.0
max_dbe = 40.0
mz_error_score_weight = 0.6
isotopologue_score_weight = 0.4
adduct_atoms_neg = [ "Cl", "Br",]
adduct_atoms_pos = [ "Na", "K",]
score_methods = [ "S_P_lowest_error", "N_S_P_lowest_error", "lowest_error", "prob_score", "air_filter_error", "water_filter_error", "earth_filter_error",]
score_method = "prob_score"
output_min_score = 0.1
output_score_method = "All Candidates"
isRadical = true
isProtonated = true
isAdduct = false
ionization_type = "ESI"
min_ppm_error = -3
max_ppm_error = 5
min_abun_error = -30
max_abun_error = 70
mz_error_range = 1
error_method = "None"
mz_error_average = 0

[Transient]
implemented_apodization_function = [ "Hamming", "Hanning", "Blackman", "Full-Sine", "Half-Sine", "Kaiser", "Half-Kaiser",]
apodization_method = "Hanning"
number_of_truncations = 0
number_of_zero_fills = 1
next_power_of_two = false
kaiser_beta = 8.6

[MassSpectrum]
threshold_method = "relative_abundance"
implemented_noise_threshold_methods = [ "minima", "signal_noise", "relative_abundance", "absolute_abundance", "log",]
noise_threshold_std = 3
s2n_threshold = 4.0
relative_abundance_threshold = 30
absolute_abundance_threshold = 1000000.0
log_nsigma = 6
log_nsigma_corr_factor = 0.463
log_nsigma_bins = 500
min_noise_mz = 50.0
max_noise_mz = 1200.0
min_picking_mz = 50.0
max_picking_mz = 1200.0
calib_minimize_method = "Powell"
calib_pol_order = 2
max_calib_ppm_error = 10
min_calib_ppm_error = -10
calib_sn_threshold = 2.0
do_calibration = true

[MassSpecPeak]
kendrick_rounding_method = "floor"
implemented_kendrick_rounding_methods = [ "floor", "ceil", "round",]
peak_derivative_threshold = 0.0
peak_min_prominence_percent = 1
min_peak_datapoints = 5.0
peak_max_prominence_percent = 0.1
peak_height_max_percent = 10.0

[MolecularFormulaSearch.usedAtoms]
C = [ 1, 100,]
H = [ 4, 200,]
O = [ 1, 22,]

[MolecularFormulaSearch.used_atom_valences]
C = 4
13C = 4
N = 3
O = 2
S = 2
H = 1
F = 0
Cl = 0
Br = [ 1, 0,]
I = [ 1, 0,]
At = 1
Li = [ 1, 0,]
Na = [ 1, 0,]
K = [ 1, 0,]
Rb = 1
Cs = 1
Fr = 1
B = [ 4, 3, 2, 1,]
In = [ 3, 2, 1,]
Al = [ 3, 1, 2,]
P = 0
Ga = [ 3, 1, 2,]
Mg = [ 2, 1,]
Be = [ 2, 1,]
Ca = [ 2, 1,]
Sr = [ 2, 1,]
Ba = 2
Ra = 2
V = [ 5, 4, 3, 2, 1,]
Fe = [ 3, 2, 4, 5, 6,]
Si = [ 4, 3, 2,]
Sc = [ 3, 2, 1,]
Ti = [ 4, 3, 2, 1,]
Cr = [ 1, 2, 3, 4, 5, 6,]
Mn = [ 1, 2, 3, 4, 5, 6, 7,]
Co = [ 1, 2, 3, 4, 5,]
Ni = [ 1, 2, 3, 4,]
Cu = [ 2, 1, 3, 4,]
Zn = [ 2, 1,]
Ge = [ 4, 3, 2, 1,]
As = [ 5, 3, 2, 1,]
Se = [ 6, 4, 2, 1,]
Y = [ 3, 2, 1,]
Zr = [ 4, 3, 2, 1,]
Nb = [ 5, 4, 3, 2, 1,]
Mo = [ 6, 5, 4, 3, 2, 1,]
Tc = [ 7, 6, 5, 4, 3, 2, 1,]
Ru = [ 8, 7, 6, 5, 4, 3, 2, 1,]
Rh = [ 6, 5, 4, 3, 2, 1,]
Pd = [ 4, 2, 1,]
Ag = [ 0, 1, 2, 3, 4,]
Cd = [ 2, 1,]
Sn = [ 4, 2,]
Sb = [ 5, 3,]
Te = [ 6, 5, 4, 2,]
La = [ 3, 2,]
Hf = [ 4, 3, 2,]
Ta = [ 5, 4, 3, 2,]
W = [ 6, 5, 4, 3, 2, 1,]
Re = [ 4, 7, 6, 5, 3, 2, 1,]
Os = [ 4, 8, 7, 6, 5, 3, 2, 1,]
Ir = [ 4, 8, 6, 5, 3, 2, 1,]
Pt = [ 4, 6, 5, 3, 2, 1,]
Au = [ 3, 5, 2, 1,]
Hg = [ 1, 2, 4,]
Tl = [ 3, 1,]
Pb = [ 4, 2,]
Bi = [ 3, 1, 5,]
Po = [ 2, 4, 6,]
Ac = [ 3, 2,]

[MassSpecPeak.kendrick_base]
C = 1
H = 2

[DataInput.header_translate]
"m/z" = "m/z"
mOz = "m/z"
Mass = "m/z"
"Resolving Power" = "Resolving Power"
"Res." = "Resolving Power"
Intensity = "Peak Height"
I = "Peak Height"
Abundance = "Peak Height"
"Signal/Noise" = "S/N"
"S/N" = "S/N"
abs_abu = "Peak Height"
sn = "S/N"
resolution = "Resolving Power"
